### ISSUE TITLE
Missing credits

### ISSUE THREAD

**Issue by basraayman** [alioualarbi/D2-usb-matchmaking#1]
The uploaded file seems to be an extremely close copy of other ones such as https://github.com/Fil93z/D2New, https://github.com/iiBerserk/Destiny-2-Matchmaking-Firewall, https://github.com/nightmaregod143/trialsfirewall and plenty of others but is missing the line with the original credits which is not allowed according to the original MIT license this code was published under. Please add the missing credits.

**Comment by alioualarbi** [comment]
Thank you Raayman,

added the credit note
