### ISSUE TITLE
-

### ISSUE THREAD

**Issue by yanbxr** [alioualarbi/D2-usb-matchmaking#3]
This is a fork from my [guide](https://github.com/yanbxr/d2hosting)
Please credit me, [@yanbxr](https://github.com/yanbxr) 
Code for my username: `[@yanbxr](https://github.com/yanbxr)`

**Comment by yanbxr** [comment]
Up

**Comment by yanbxr** [comment]
Sad

**Comment by alioualarbi** [comment]
Sorry bro add you, however tried to use it Openvpn but no luck can insight how the setup is done and how your PS4s are linked physically?

**Comment by yanbxr** [comment]
XR500
